version: '3'

services:
  php:
    image: rr-grpc:1.0.0
    build:
      context: '.'
      dockerfile: './docker/php/Dockerfile'
    ports:
      - 8889:9001
      # http://localhost:8889
    volumes:
      - './:/app'
    tty: true
    working_dir: '/app'

  ruby:
    image: rr-grpc-client:1.0.0
    build:
      context: '.'
      dockerfile: './docker/ruby/Dockerfile'
    # ports:
      # - 8889:9001
      # http://localhost:8889
    volumes:
      - './:/app'
    tty: true
    working_dir: '/app'

  protoc:
    image: rr-grpc-protoc:1.0.0
    build:
      context: '.'
      dockerfile: './docker/protoc/Dockerfile'
    # ports:
      # - 8889:9001
      # http://localhost:8889
    volumes:
      - './:/app'
    tty: true
    working_dir: '/app'


  grpc-curl:
    image: fullstorydev/grpcurl:latest
    tty: true

  # mysql:
  #   image: 'mysql:8.0'
  #   ports:
  #     - '3336:3306'
  #   expose:
  #     - 3336
  #   environment:
  #     MYSQL_DATABASE: sample
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #     MYSQL_TCP_PORT: 3336
  #   volumes:
  #     - mysql_volume:/var/lib/mysql
  #     - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  # phpmyadmin:
  #   image: 'phpmyadmin/phpmyadmin'
  #   ports:
  #     - '2223:80'
  #     # http://localhost:2223  user: root, pass: ''
  #   environment:
  #     PMA_HOST: 'mysql'
  #     PMA_PORT: '3336'
  #   depends_on:
  #     - mysql


# volumes:
#   mysql_volume:
#     driver: local
