# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service.proto for package 'service'

require 'grpc'
require 'service_pb'

module Service
  module Echo
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'service.Echo'

      rpc :Ping, ::Service::Message, ::Service::Message
    end

    Stub = Service.rpc_stub_class
  end
end
