# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service.proto", :syntax => :proto3) do
    add_message "service.Message" do
      optional :msg, :string, 1
    end
  end
end

module Service
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("service.Message").msgclass
end
